trigger: none

resources:
  repositories:
    - repository: devRepo
      type: github
      name: raomahima612-cmd/stellarai-dev-dummy
      endpoint: github.com_raomahima612-cmd

pool:
  name: Default

steps:
- checkout: self
  displayName: 'Checkout QA Automation Repo'

- script: |
    mvn clean test -f QA_Repo/pom.xml
  displayName: 'Run StellarAI Selenium Tests'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    failTaskOnFailedTests: true
  condition: succeededOrFailed()
  displayName: 'Publish Test Results'
